feat: check whoami before other requests
ydb-platform/ydb-embedded-ui pull request #1103
Opened 2024-08-01 16:33 UTC by artemmufazalov

Closes #935

2024-08-01 16:36 UTC, artemmufazalov commented on src/services/api.ts
> +                return Promise.reject(error);
`window.location.assign` doesn't happen immediately, return error so some normal error will be shown in between

2024-08-01 16:38 UTC, artemmufazalov commented on src/services/api.ts
> +                window.location.assign(response.data.authUrl);
`window.location.assign` doesn't happen immediately, return error so some normal error will be shown in between

2024-08-02 08:20 UTC, ValeraS requested changes

2024-08-02 08:20 UTC, ValeraS commented on src/containers/App/Content.tsx
> +    return children;
```js
<LoaderWrapper loading={isLoading}>
    <PageError error={error}>
        {children}
    </PageError>
</LoaderWrapper>
```

2024-08-02 08:20 UTC, ValeraS commented on src/store/utils.ts
>  import createToast from '../utils/createToast';
we can delete this file now.

2024-08-02 11:07 UTC, ValeraS submitted a review, later dismissed

2024-08-02 12:03 UTC, ValeraS submitted a review, later dismissed

2024-08-02 14:33 UTC, artemmufazalov commented on playwright.config.ts
> +    },
Since we now await whoami before loading pages, default timeout isn't enough

2024-08-02 14:49 UTC, artemmufazalov commented
I will fix flaky tenants test in a separate PR. It seems, since page content is now loaded only after `whoami` finish, test needs more time

2024-08-02 14:55 UTC, ValeraS approved these changes

2024-08-02 14:57 UTC, merged