feat(Header): use cluster domain if cluster name is undefined
ydb-platform/ydb-embedded-ui pull request #1271
Opened 2024-09-09 12:35 UTC by Raubzeug

closes #1252 

[Stand](https://nda.ya.ru/t/aV814vaJ7882cz)

## CI Results

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1271/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 124 | 119 | 0 | 5 | 0 |

### Bundle Size: ✅
Current: 78.86 MB | Main: 78.86 MB
Diff: +0.00 MB (0.00%)

✅ Bundle size unchanged.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

2024-09-11 12:43 UTC, artemmufazalov approved these changes

2024-09-11 14:07 UTC, ValeraS requested changes

2024-09-11 14:07 UTC, ValeraS commented on src/store/reducers/cluster/cluster.ts
> +    const {currentData: baseClusterInfo} = clusterApi.useGetClusterInfoQuery(
Does this query contain info form getClusterBaseInfo? Why do use both?

2024-09-12 10:56 UTC, artemmufazalov submitted a review, later dismissed

2024-09-12 16:10 UTC, ValeraS requested changes

2024-09-12 16:10 UTC, ValeraS commented on src/store/reducers/cluster/cluster.ts
> +        setClusterTitle: (state, action: PayloadAction<string>) => {
Let's add only selector, something like this:

```ts
const createClusterInfoSelector = createSelector(
    (clusterName?: string) => clusterName,
    (clusterName) => clusterApi.endpoints.getClusterInfo.select(clusterName),
);

export const selectClusterInfo = createSelector(
    (state: RootState) => state,
    (_state: RootState, clusterName?: string) => createClusterInfoSelector(clusterName),
    (state, selectGetTopic) => selectGetTopic(state).data,
);

export const selectClusterTitle = createSelector(
    (_state: RootState, clusterName?: string) => clusterName,
    (state: RootState, clusterName?: string) => selectClusterInfo(state, clusterName),
    (clusterName, clusterInfo) => {
        const {Name, Domain} = clusterInfo?.clusterData || {};

        return Name || clusterName || normalizeDomain(Domain) || CLUSTER_DEFAULT_TITLE;
    },
);
```

2024-09-13 08:35 UTC, ValeraS requested changes

2024-09-13 08:35 UTC, ValeraS commented on src/containers/Cluster/Cluster.tsx
> +    const clusterTitle = useTypedSelector(selectClusterTitle);
```suggestion
    const clusterTitle = useTypedSelector((state) => selectClusterTitle(state, clusterName ?? undefined));
```

2024-09-13 09:16 UTC, ValeraS approved these changes

2024-09-13 10:59 UTC, artemmufazalov approved these changes

2024-09-13 11:10 UTC, merged