feat: add storage group page
ydb-platform/ydb-embedded-ui pull request #1289
Opened 2024-09-12 13:07 UTC by astandrik

[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/cluster/storage)

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1159

## CI Results

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1289/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 124 | 116 | 0 | 8 | 0 |

### Bundle Size: 🔺
Current: 78.96 MB | Main: 78.84 MB
Diff: +0.12 MB (0.15%)

⚠️ Bundle size increased. Please review.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

2024-09-12 15:32 UTC, artemmufazalov requested changes

2024-09-12 15:32 UTC, artemmufazalov commented on src/containers/StorageGroupPage/StorageGroupPage.scss
> +}
You don't have `controls`, `group-disks` and `group-disk` on this page

2024-09-12 15:32 UTC, artemmufazalov commented on src/components/StorageGroupInfo/i18n/en.json
> +  "storage-group-title": "Storage Group",
Redundant field

2024-09-12 15:32 UTC, artemmufazalov commented on src/components/StorageGroupInfo/i18n/en.json
> +  "allocation-units": "Units",
Why do you need both?

2024-09-17 07:02 UTC, Raubzeug commented
A bug when scrolling:

<img width="1354" alt="Screenshot 2024-09-17 at 09 59 08" src="https://github.com/user-attachments/assets/e6a74a96-b89a-4760-b13b-a3393fe568e2">

2024-09-17 07:26 UTC, Raubzeug requested changes

2024-09-17 07:26 UTC, Raubzeug commented on src/components/StorageGroupInfo/StorageGroupInfo.tsx
> +            value: `${LatencyPutTabletLog} ms`,
Here and farther lets add spaces between the digits of the number (like it is done in `Available Space` field)

2024-09-17 07:26 UTC, Raubzeug commented on src/components/StorageGroupInfo/StorageGroupInfo.tsx
> +        <div className={b('wrapper', className)}>
lets use `Flex` component

2024-09-17 07:26 UTC, Raubzeug commented on src/components/StorageGroupInfo/StorageGroupInfo.tsx
> +            <div className={b('col')}>
do we need this wrapper?

2024-09-17 07:26 UTC, Raubzeug commented on src/containers/StorageGroupPage/StorageGroupPage.tsx
> +        <div className={storageGroupPageCn()}>
`Flex`?

2024-09-17 12:51 UTC, Raubzeug approved these changes

2024-09-17 17:21 UTC, artemmufazalov approved these changes

2024-09-17 17:36 UTC, merged