refactor: split nodes columns file, use nodes api, update types
ydb-platform/ydb-embedded-ui pull request #1310
Opened 2024-09-17 17:23 UTC by artemmufazalov

2024-09-17 17:30 UTC, artemmufazalov commented on src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByCpu.tsx
> +    const {currentData, isFetching, error} = nodesApi.useGetNodesQuery(
Made all nodes tables use the same api. This way they will have single cache entry and single prepare function

2024-09-17 17:31 UTC, artemmufazalov commented on src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/utils.ts
> +}
In the latest `viewer/nodes` updates some sort params was removed from backend. Implemented additional sorting and filtered on frontend to ensure correct results

2024-09-17 17:32 UTC, artemmufazalov commented on src/types/api/nodes.ts
> +export interface NodesRequestParams {
Described all params, that are currently available on backend

2024-09-17 17:33 UTC, artemmufazalov commented on src/containers/Nodes/columns/constants.ts
> +export const NODES_COLUMNS_IDS = {
Just prepared columns files for further updates

2024-09-18 14:32 UTC, astandrik requested changes

2024-09-18 14:32 UTC, astandrik commented on src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByLoad.tsx
> +    const topNodes = prepareTopNodesByLoad(currentData);
would React.memo be a good idea here?

2024-09-18 14:32 UTC, astandrik commented on src/containers/Storage/utils/index.ts
> +    sortValue: 'NodeId',
NODES_COLUMNS_IDS.NodeId ?

2024-09-19 10:38 UTC, astandrik approved these changes

2024-09-19 10:50 UTC, merged