chore: do not hide pdisk and vdisk popups if mouse on popup content
ydb-platform/ydb-embedded-ui pull request #1435
Opened 2024-10-10 11:27 UTC by astandrik

2024-10-10 11:43 UTC, artemmufazalov commented
Please, change PR title prefix to `fix:`, so it will appear in Changelog

2024-10-10 11:43 UTC, artemmufazalov approved these changes

2024-10-10 11:50 UTC, astandrik commented
@artemmufazalov added debounce cancelation to prevent appearing not needed popups on fast mast movement

2024-10-10 11:53 UTC, artemmufazalov approved these changes

2024-10-10 12:22 UTC, astandrik commented
@Raubzeug added delay for table cells as discussed

2024-10-10 12:25 UTC, astandrik commented
Deployed stand for testing

2024-10-10 14:46 UTC, Raubzeug requested changes

2024-10-10 14:46 UTC, Raubzeug commented on src/components/VDiskPopup/VDiskPopup.tsx
> +    const [isPopupOpen, setIsPopupOpen] = React.useState(props.open);
same here

2024-10-11 06:35 UTC, Raubzeug approved these changes

2024-10-11 08:19 UTC, merged