feat: use modern query schema
ydb-platform/ydb-embedded-ui pull request #159
Opened 2022-09-08 23:43 UTC by ariser

2022-09-09 00:05 UTC, ariser commented on src/components/QueryResultTable/QueryResultTable.tsx
> +            rowKey={(_, index) => index}
to myself: remember to check this

2022-09-09 12:31 UTC, Raubzeug commented
1) App crashes when click "Explain query".
2) Always Bad Request error when try to see preview.

2022-09-09 12:31 UTC, Raubzeug requested changes

2022-09-09 19:43 UTC, ariser commented
> App crashes when click "Explain query".

Thank you for noticing! This is not caused by the changes in this PR, but it is connected to the corresponding backend changed. Will discuss this to make sure we preserve backward compatibility.

> Always Bad Request error when try to see preview.

This does not reproduce for me. Let's discuss this in PM if this is still an issue.

2022-09-09 19:47 UTC, ariser commented on src/utils/query.ts
> +            return 'boolean';
I can add those, but I don't see an important reason why
I doubt type "number" will ever change to anything else :)
If you're convinced we should have them, can you explain in more detail?
Also, I renamed this function to `getColumnType` — if this changes anything for you

2022-09-12 12:28 UTC, Raubzeug commented on src/utils/query.ts
> +            return 'boolean';
Np, it is not critical at all. I just don't like string constants, but it's up to you of course!

2022-09-12 13:14 UTC, Raubzeug submitted a review, later dismissed

2022-09-12 13:16 UTC, Raubzeug approved these changes

2022-09-12 13:55 UTC, merged