fix(Storage): encouraging message for empty filtered lists
ydb-platform/ydb-embedded-ui pull request #176
Opened 2022-09-23 15:13 UTC by ariser

Before:
<img src="https://user-images.githubusercontent.com/3864424/191994157-4ff36cbc-e83a-4235-acd6-3a3de5dece59.png" width="1039"/>

After:
<img src="https://user-images.githubusercontent.com/3864424/191993868-53ea91cb-b330-45de-8c4b-307fe6b2ce7b.png" width="1032"/>

2022-09-23 15:17 UTC, ariser commented on src/containers/Tenant/Diagnostics/Network/Network.scss
> +        margin: 0 16px 16px 0;
The right margin on empty lists was forced by the image, now that it became smaller, the layout squashed. This fixes it.

2022-09-23 15:33 UTC, Raubzeug requested changes

2022-09-23 15:33 UTC, Raubzeug commented on src/containers/Storage/StorageGroups/StorageGroups.tsx
> +                description="Everyting is fine!"
Should we use here i18n?

2022-09-23 15:33 UTC, Raubzeug commented on src/containers/Storage/StorageGroups/StorageGroups.tsx
> +            emptyDataMessage={'No such groups'}
i18n?

2022-09-23 15:33 UTC, Raubzeug commented on src/containers/Storage/StorageGroups/StorageGroups.tsx
> +    const renderEmptyState = (message: string) => {
Lets move it to the separate component!

2022-09-26 10:04 UTC, ariser commented on src/containers/Storage/EmptyFilter/EmptyFilter.tsx
> +                key="show-all"
Is there a reason it should be here?

2022-09-26 11:20 UTC, Raubzeug approved these changes

2022-09-26 11:20 UTC, Raubzeug commented on src/containers/App/App.scss
> +    width: 200px;
May be this class should be moved to Illustration component too?

2022-09-26 11:20 UTC, Raubzeug commented on src/containers/Storage/EmptyFilter/EmptyFilter.tsx
> +                key="show-all"
Sorry, overthought a bit :)

2022-09-26 11:43 UTC, Raubzeug approved these changes

2022-09-26 11:47 UTC, merged