feat: display view query text
ydb-platform/ydb-embedded-ui pull request #1761
Opened 2024-12-17 16:37 UTC by astandrik

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1755
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/919

2024-12-18 13:48 UTC, Raubzeug commented
Lets try to use Monaco because now we have different query colorization, and this may be confusing.

2024-12-19 17:53 UTC, astandrik commented
@Raubzeug 

Implemented using readonly MonacoEditor with some custom options

2024-12-20 07:10 UTC, Raubzeug commented
Lets show buttons on the right, without shrinking the editor.
<img width="919" alt="Screenshot 2024-12-20 at 09 49 27" src="https://github.com/user-attachments/assets/d58c4347-9b5d-44be-ad40-64890bd90b4e" />

2024-12-20 07:10 UTC, Raubzeug requested changes

2024-12-20 07:10 UTC, Raubzeug commented on src/components/TruncatedQuery/TruncatedQuery.tsx
> +        <CellWithPopover
It seems that popover is now redundant, because we don't truncate query any more.

2024-12-20 07:10 UTC, Raubzeug commented on src/containers/Tenant/Diagnostics/TopQueries/columns/columns.tsx
> +            <TruncatedQuery value={row.QueryText?.toString()} />
<img width="815" alt="Screenshot 2024-12-20 at 10 00 03" src="https://github.com/user-attachments/assets/30433d0f-f2a3-4f31-90ed-03a9c24405a8" />

2024-12-20 07:10 UTC, Raubzeug commented on src/components/Snippet/Snippet.tsx
> +                    height={SNIPPET_LENGTH * 20}
Let's make a variable height with maximum `SNIPPET_LENGTH * 20`

For example, here such height looks redundant.
<img width="963" alt="Screenshot 2024-12-20 at 10 07 00" src="https://github.com/user-attachments/assets/9c8a3166-57c1-4de0-aa3b-4f4f404573cf" />

2024-12-20 10:04 UTC, artemmufazalov commented
Syntax is highlighted with a delay

<img width="972" alt="Screenshot 2024-12-20 at 13 02 06" src="https://github.com/user-attachments/assets/a4568a9d-2e0b-401b-bd0d-e206dee059ca" />

2024-12-20 11:21 UTC, closed without merging