refactor(Tooltip): migrate reducer to ts
ydb-platform/ydb-embedded-ui pull request #246
Opened 2022-12-08 16:06 UTC by artemmufazalov

2022-12-08 17:01 UTC, ariser requested changes

2022-12-09 07:45 UTC, artemmufazalov commented on src/utils/tooltip.js
> +                            ))}
It was made by prettier)

2022-12-09 09:15 UTC, ariser approved these changes

2022-12-09 09:17 UTC, ariser commented on src/utils/tooltip.js
> +                            ))}
seemed unlikely that this was the only place prettier didn't like of all this file :)

2022-12-09 11:31 UTC, ariser approved these changes

2022-12-09 12:48 UTC, merged