fix(TabletsStatistic): process different tablets state types
ydb-platform/ydb-embedded-ui pull request #266
Opened 2022-12-29 13:45 UTC by artemmufazalov

2023-01-11 16:02 UTC, ariser requested changes

2023-01-11 16:02 UTC, ariser commented on src/utils/tablet.ts
> +    (acc, curr) => {
a destructurisation here would be more readable 
```
(acc, [state, color]) => ...
```

2023-01-12 09:43 UTC, artemmufazalov commented on src/utils/tablet.ts
> +    if (Object.values(EFlag).includes(state as EFlag)) {
In this case there still will be a type cast in `Object.values(EFlag).includes(value as EFlag)`. So, my way to do it seems  more concise

2023-01-12 12:17 UTC, ariser approved these changes

2023-01-12 14:25 UTC, artemmufazalov commented on src/utils/tablet.ts
> +    if (Object.values(EFlag).includes(state as EFlag)) {
I forgot about last type cast. And now I agree with you. So, fixed

2023-01-12 14:40 UTC, ariser approved these changes

2023-01-12 14:42 UTC, merged