feat(QueryEditor): enable explain query modes
ydb-platform/ydb-embedded-ui pull request #361
Opened 2023-04-18 14:37 UTC by artemmufazalov

Connected PRs:
- #360
- #362
- #363 
- #364 
- #367 
- #369

2023-04-26 14:11 UTC, artemmufazalov commented on src/containers/Tenant/QueryEditor/QueryExplain/QueryExplain.js
> -    useEffect(() => {
It occurred, that `explain-ast` is run in data-query mode, so when we request `ast` for `explain-scan` or `explain-query`, we have `ast` that does not correspond to initial mode. Thus, it should be displayed only if query response have it

2023-04-26 14:14 UTC, artemmufazalov commented on src/containers/Tenant/QueryEditor/QueryEditorControls/QueryEditorControls.scss
> +.ydb-query-editor-controls {
These styles was moved from `QueryEditor.scss` with minor changess (e.g. `&__mode-selector` was added)

2023-04-26 14:15 UTC, artemmufazalov commented on src/containers/Tenant/QueryEditor/QueryEditor.js
> +    sendExecuteQuery,
It was just renamed

2023-04-26 14:21 UTC, artemmufazalov commented on src/store/reducers/executeQuery.ts
> -    runAction: readSavedSettingsValue(QUERY_INITIAL_RUN_ACTION_KEY, RUN_ACTIONS_VALUES.script),
Selected query mode is now managed inside `QueryEditor` component

2023-04-27 07:58 UTC, Raubzeug commented
When the new mode is enabled, it is unclear, what action is produced by the button `Type: Script | Scan` (actually, no action). I would better make this button similar with query type selection (in the old mode).

![0EEB6DB9-FB6B-4BDE-B3E1-871F644EE16D](https://user-images.githubusercontent.com/42094364/234797730-ef578268-ff4b-4ac8-be65-69e1e8c702c4.jpeg)

2023-04-27 08:03 UTC, Raubzeug requested changes

2023-04-27 08:12 UTC, artemmufazalov commented on src/containers/Tenant/QueryEditor/QueryEditor.js
>          savedQueries: parseJson(getSettingValue(state, SAVED_QUERIES_KEY)),
We don't need to parse value if it used as a string value, so `getSettingValue` doesn't always go with `parseJson` . As for me, adding some additional `getParsedSettingValue` helper will not make code easier as it won't be clear when it should be used and when we should use just `getSettingValue`

2023-04-27 08:16 UTC, Raubzeug commented on src/containers/Tenant/QueryEditor/QueryEditor.js
>          savedQueries: parseJson(getSettingValue(state, SAVED_QUERIES_KEY)),
I suggested having two helpers! But it's totally up to you!
Unfortunately now it is not clear too - when we should parse JSON, and when value is a plain string... What if add `try ... catch`? If `JSON.parse` fails, return unparsed value, and if succeed - return parsed.

2023-04-28 08:26 UTC, artemmufazalov commented on src/containers/Tenant/QueryEditor/QueryEditor.js
>          savedQueries: parseJson(getSettingValue(state, SAVED_QUERIES_KEY)),
Agree with you, now it's unclear too. Added additional parser, maybe I'll replace old one with it when I'll be refactoring

2023-04-28 14:23 UTC, Raubzeug approved these changes

2023-04-28 15:05 UTC, Raubzeug approved these changes

2023-04-28 15:07 UTC, merged