feat: remove support for explain v0.1
ydb-platform/ydb-embedded-ui pull request #363
Opened 2023-04-19 09:03 UTC by artemmufazalov

2023-04-19 09:29 UTC, artemmufazalov commented on src/store/reducers/explainQuery.ts
> +                        pristine: result,
`pristine` is displayed in explain JSON tab

2023-04-19 14:01 UTC, Raubzeug requested changes

2023-04-20 10:47 UTC, artemmufazalov commented on src/store/reducers/explainQuery.ts
> +export const getExplainQueryAst = ({query, database}: {query: string; database: string}) => {
I don't like the idea of the general type for these two fetches. They are similar now, but they will have different argument types when explain modes (scan / script) will be added

2023-04-21 13:43 UTC, Raubzeug approved these changes

2023-04-21 13:46 UTC, Raubzeug approved these changes

2023-04-21 13:50 UTC, merged