feat(QueryEditor): add data and query modes
ydb-platform/ydb-embedded-ui pull request #422
Opened 2023-06-09 13:59 UTC by artemmufazalov

2023-06-09 14:07 UTC, artemmufazalov commented on src/types/api/query.ts
Renamed `ScanPlan`, `ExplainScan`, `ExecuteScan` to `QueryPlan`, `ExplainQuery` and `ExecuteQuery` correspondingly as they correspond to `meta.type = "query"`

2023-06-09 14:42 UTC, Raubzeug requested changes

2023-06-09 14:42 UTC, Raubzeug commented on src/containers/Tenant/QueryEditor/QueryEditorControls/OldQueryEditorControls.tsx
> +    useEffect(() => {
I don't think this logic should be here. Component should not be aware about "another" modes. As for me, `queryMode` should be calculated in selector.

2023-06-13 08:42 UTC, Raubzeug approved these changes

2023-06-13 08:46 UTC, Raubzeug approved these changes

2023-06-13 08:50 UTC, merged