feat(Tenant): transform general tabs into left navigation items
ydb-platform/ydb-embedded-ui pull request #431
Opened 2023-06-21 08:50 UTC by artemmufazalov

2023-06-23 08:43 UTC, Raubzeug commented
1) It doesn't warn user about unsaved changes in query editor.
2) If I run query and thereafter change database, query text is still in editor, but query doesn't work. It seems that editor should be cleared upon change database.

2023-06-23 08:55 UTC, Raubzeug requested changes

2023-06-23 08:55 UTC, Raubzeug commented on src/containers/AsideNavigation/AsideNavigation.tsx
> +    const [initiaTenantTab, setTenantInitialTab] = useSetting<string>(
typo `initia`

2023-06-23 08:55 UTC, Raubzeug commented on src/containers/AsideNavigation/AsideNavigation.tsx
> +import {TENANT_GENERAL_TABS_IDS} from '../../store/reducers/tenant/constants';
Its no longer tabs. Maybe it should be renamed in separate PR or here in additional commit?

2023-06-23 08:55 UTC, Raubzeug commented on src/containers/AsideNavigation/AsideNavigation.tsx
> +    const isTenantPage = pathname === '/tenant';
Lets start to move app paths into variables?

2023-06-23 14:45 UTC, artemmufazalov commented
> 1. It doesn't warn user about unsaved changes in query editor.

It doesn't warn in two cases:
1) there is no such query in queries history (only last item is checked). So if you run query, then try to reload, it doesn't warn, yes. But this query will be the last in history
```
const hasUnsavedInput = input
            ? input !== history.queries[history.queries?.length - 1]
            : false;
```
2) if active window isn't `QueryEditor`. I'm not sure, that we should warn in such cases

2023-06-26 06:54 UTC, Raubzeug commented
> 1. there is no such query in queries history (only last item is checked). So if you run query, then try to reload, it doesn't warn, yes. But this query will be the last in history

Thats correct behaviour.

> 2\. if active window isn't `QueryEditor`. I'm not sure, that we should warn in such cases

We should warn that time, when unsaved content in editor is going to be lost. (reseted or replaced) 

The usecase: I'd written something in the editor (I had not run it), and after that I moved to the cluster's root and to another database. Content in editor is lost, but I was't warned about it :(

2023-06-26 09:08 UTC, artemmufazalov commented
> We should warn that time, when unsaved content in editor is going to be lost. (reseted or replaced)
> 
> The usecase: I'd written something in the editor (I had not run it), and after that I moved to the cluster's root and to another database. Content in editor is lost, but I was't warned about it :(

It seems like a big issue with several scenarios:
1. Top Queries, History and Saved Tabs
2. Schema actions (create, select, upsert and etc.)
3. Navigation from Tenant page
4. Browser actions (page reload)

I couldn't figure out fast and easy solution, so I'd prefer to tackle this issue separately. There is a ticket for it already, I'll send it to you in PM

2023-06-26 09:13 UTC, Raubzeug approved these changes

2023-06-26 09:15 UTC, merged