chore(AsideNavigation): add i18n
ydb-platform/ydb-embedded-ui pull request #559
Opened 2023-10-13 14:53 UTC by artemmufazalov

![Screen Shot 2023-10-13 at 17 52 49](https://github.com/ydb-platform/ydb-embedded-ui/assets/67755036/1922d93e-8a5e-4f94-bc0e-2104d331f058)

2023-10-16 06:13 UTC, krosy1337 requested changes

2023-10-16 06:13 UTC, krosy1337 commented on src/containers/AsideNavigation/i18n/en.json
> +  "logo.title": "YDB",
Why did you put the logo title in i18n?

2023-10-16 09:01 UTC, artemmufazalov commented on src/containers/AsideNavigation/i18n/en.json
> +  "logo.title": "YDB",
I guess, automatically)

2023-10-18 04:49 UTC, krosy1337 approved these changes

2023-10-18 08:37 UTC, merged