feat: use VirtualTable in Nodes and Diagnostics
ydb-platform/ydb-embedded-ui pull request #678
Opened 2024-01-31 10:10 UTC by artemmufazalov

2024-02-01 07:56 UTC, Raubzeug requested changes
When I switch between Nodes and Storage tabs, it is always revoked 2 similar request.

2024-02-01 09:22 UTC, artemmufazalov commented
> When I switch between Nodes and Storage tabs, it is always revoked 2 similar request.

This issue was addressed here: https://github.com/ydb-platform/ydb-embedded-ui/pull/676

2024-02-01 11:54 UTC, Raubzeug commented
> > When I switch between Nodes and Storage tabs, it is always revoked 2 similar request.
> 
> This issue was addressed here: #676

Agrh, I always forget abt it >_<

2024-02-01 11:54 UTC, Raubzeug approved these changes

2024-02-05 12:11 UTC, Raubzeug approved these changes

2024-02-05 12:22 UTC, merged