feat: add YQL autocomplete
ydb-platform/ydb-embedded-ui pull request #755
Opened 2024-03-12 08:46 UTC by Raubzeug

Closes #611

2024-03-13 09:43 UTC, artemmufazalov requested changes

2024-03-13 15:16 UTC, Raubzeug commented on src/utils/monaco.ts
> +        provideCompletionItems: createProvideSuggestionsFunction(database),
I decided to do it in the closest place to `tenantName` emergence.

2024-03-13 17:36 UTC, Raubzeug commented on src/utils/monaco.ts
> +        provideCompletionItems: createProvideSuggestionsFunction(database),
Do you suggest to lift query string parsing from `ObjectGeneral` to `Tenant`? As for me it make sense.

2024-03-13 17:42 UTC, artemmufazalov commented on src/utils/monaco.ts
> +        provideCompletionItems: createProvideSuggestionsFunction(database),
Yes. 

There is already query parsing in `Tenant`, `tenantName` could be passed in props

2024-03-14 09:19 UTC, artemmufazalov submitted a review, later dismissed

2024-03-14 11:59 UTC, artemmufazalov approved these changes

2024-03-14 12:10 UTC, merged