feat: suggest views and table settings
ydb-platform/ydb-embedded-ui pull request #864
Opened 2024-05-31 15:24 UTC by Raubzeug

2024-05-31 15:26 UTC, Raubzeug commented
closes #858

2024-06-03 10:40 UTC, artemmufazalov approved these changes

2024-06-03 10:44 UTC, artemmufazalov requested changes
`CREATE VIEW my_view WITH () AS SELECT 1;`

In `WITH` section settings for tables are suggested

2024-06-04 10:50 UTC, artemmufazalov commented on src/utils/monaco/yql/constants.ts
> +    ],
Topic settings are not suggested

2024-06-04 14:49 UTC, artemmufazalov commented on src/utils/monaco/yql/generateSuggestions.ts
> +    const tableHints = await getEntitySettings(entityType);
Please, rename `tableHints` to `entityHints`

2024-06-04 14:52 UTC, artemmufazalov approved these changes

2024-06-04 16:02 UTC, merged