fix: expand the column 'degraded' width
ydb-platform/ydb-embedded-ui pull request #962
Opened 2024-07-01 11:26 UTC by walborn

closes #949

2024-07-01 11:58 UTC, Raubzeug commented
In `usageColumn` please set:
```
minWidth: 75;
resizeMinWidth: 75;
```

2024-07-01 11:59 UTC, Raubzeug requested changes

2024-07-02 08:14 UTC, artemmufazalov approved these changes

2024-07-02 08:16 UTC, Raubzeug approved these changes

2024-07-02 08:16 UTC, merged